{{- $root := . -}}
{{- range .Values.applications }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: {{ . }}
spec:
  project: {{ $root.Values.config.project }}
  source:
    targetRevision: {{ $root.Values.config.targetRevision }}
    repoURL: "{{ $root.Values.config.baseUrl }}{{ . }}.git"
    path: helm/{{ . | trimPrefix "demo-" }}
  destination:
    server: {{ $root.Values.config.cluster }}
    namespace: {{ $root.Values.config.namespace }}
  syncPolicy:
    prune: {{ $root.Values.sync.prune }}
    selfHeal: {{ $root.Values.sync.selfHeal }}
    allowEmpty: {{ $root.Values.sync.allowEmpty }}
  {{- if $root.Values.sync.enabled }}
  syncPolicy:
    automated:
      prune: {{ $root.Values.sync.prune }}
      selfHeal: {{ $root.Values.sync.selfHeal }}
      allowEmpty: {{ $root.Values.sync.allowEmpty }}
    syncOptions:
    - CreateNamespace={{- $root.Values.sync.createNamespace }}
    retry:
      limit: {{ $root.Values.sync.retry.limit }}
      backoff:
        duration: {{ $root.Values.sync.retry.backoff_duration }}
        factor: {{ $root.Values.sync.retry.backoff_factor }}
        maxDuration: {{ $root.Values.sync.retry.backoff_maxDuration }}
  {{ end }}
{{- end }}
