config:
  namespace: default
  baseUrl: https://github.com/fmdlc/
  cluster: https://kubernetes.default.svc
  project: default
  targetRevision: HEAD

applications:
  - demo-flask-app
  - demo-hello-world-app
