# This is a YAML-formatted file.
# ts=2

config:
  namespace: default
  baseUrl:
  cluster: https://kubernetes.default.svc
  project: default
  targetRevision: HEAD
  gitlab_url: https://github.com/fmdlc/

sync:
  enabled: true
  prune: true
  selfHeal: true
  allowEmpty: false
  createNamespace: true
  retry:
    limit: 5
    backoff_duration: 5s
    backoff_factor: 2
    backoff_maxDuration: 3m

applications:
  - demo-flask-app

